language: python

sudo: required

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


install:
  - python -m pip install -r requirements.txt

script:
  - python -m pytest --cov=./ ./tests/

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest


after_success:
  - python -m codecov

after_failure:
  - python -m codecov



